### ISSUE TITLE
contributions from sanitize.css

### ISSUE THREAD

**Issue by jonathantneal** [mozdevs/cssremedy#32]
Hi there. First, love it. I think a project like this with the momentum and long-term backing of Mozilla could be the “final form” of sanitize.css. I’d gladly contribute what I’ve learned there and deprecate that module in favor of something that could be managed by a dedicated team of developers. I’m all in favor of flavors, and I love the shout out in the README. Our projects seem extremely [aligned](https://csstools.github.io/sanitize.css/#why) in [purpose](https://github.com/mozdevs/cssremedy#what-is-this), so I think it could be a win for developers to focus my efforts here.

Also, I love that you’ve split out the quotes styling into its own file. In fact, this seems like a really intelligent way to split out opinionated work that doesn’t necessarily belong in “core”. For instance, for sanitize.css I identified `system-ui` as a preferred design pattern in unformatted documents over `serif` — I suppose this is because documents are sometimes apps. Still, it bothered me to ship this as a default to the countless sites that will only overwrite the font family with their own. So yea, moving these opinionated styles into their own files seems like the right move.

I’ll be submitting some PRs with other concepts from sanitize.css (which is licensed CC0, so there’s certainly no issues there). I’m mostly opening this issue to start a conversation about my first 2 paragraphs.

**Comment by jensimmons** [comment]
Hi Jonathan, 
I'm glad you are here. It's great to have your support. 

In fact, I have [a copy of Sanitize in the "process" directory in this project's repo](https://github.com/mozdevs/cssremedy/blob/master/process/Other_resets/2015_sanitize.css). That whole project directory is a giant to-do list of code to go through sort of hand merge — to pick through, understand, compare & contrast, and figure out what's the best choice for Remedy. 

I put the code for `<q>` in a separate file 
1) because it's a lot of code, and it'll be easier to not have it mentally cluttering up the main file, especially at first. I figure we can always merge them into one file later if we want; and 
2) because it's a lot of code. And the whole reason it's _not_ properly shipped in UA styles is because browser engineers have been hesitant to include that many KBs to support an HTML element that most websites don't even use. I figure we can have that debate later. (Should default CSS code support proper quotes in all the languages around the world, or is the performance 'cost' too much?) 

Do break out ideas from Sanitize into separate issues (as we've been doing), so we can debate each on it's own, compare to what other resets / starter files / UA styles do, understand the relevant specs, and decide what to do. 

Excellent! Glad to have you.

**Comment by mirisuzanne** [comment]
This is great! Closing to cleanup the issues…
