### ISSUE TITLE
Set line-heights on headlines

### ISSUE THREAD

**Issue by jensimmons** [mozdevs/cssremedy#9]
One of my pet peeves is when developers forget to reset the line-height on headlines, and the UA default is used. Usually this results in there being more space between wrapping lines in an h1, h2, etc than there is space between that headline and the other content before or after it. (line-height is bigger than top or bottom margin). 

In the stylesheet, for each headline, I wrote something like:
```
h2 {
  font-size: 1.5rem;
  line-height: 1;
}
```

I tossed `line-height: 1` in there as a placeholder. We should take some time to decide what value it should be. `1` is likely too tight.

**Comment by charakterziffer** [comment]
I often set the line-height for headlines reciprocally proportional to the font-size with the aim to get them sitting on a common line raster. The formula for that is `default line-height ÷ font-size`. For h1 and h6 I multiply/divide it by 1.5, because otherwise it’s too extreme. So my very opinionated line-heights would be

`h1 { font-size: 2rem; line-height: 1.125 /* 1.5 ÷ 2 (× 1.5) */ }`
`h2 { font-size: 1.5rem; line-height: 1 /* 1.5 ÷ 1.5 */ }`
`h3 { font-size: 1.17rem; line-height: 1.282 /* 1.5 ÷ 1.17 */ }`
`h4 { font-size: 1rem; line-height: 1.5 /* 1.5 ÷ 1 */ }`
`h5 { font-size: 0.833rem; line-height: 1.807 /* 1.5 ÷ 0.833 */ }`
`h6 { font-size: 0.667rem; line-height: 1.5 /* 1.5 ÷ 0.667 (÷ 1.5) */ }`

To get a visually balanced line-height in any case it has to be smaller for big text sizes and bigger for smaller text sizes. I don’t think one common line-height would fit to all headline sizes.

PS: To get the headlines sitting on a raster one also has to adjust the margins – but that clearly shouldn’t be part of this remedy.

PPS: The 0.67rem for h6 seem to be really small. Isn’t 0.75rem the usual size?

**Comment by sandren** [comment]
> I tossed `line-height: 1` in there as a placeholder. We should take some time to decide what value it should be. `1` is likely too tight.

In print design, the leading of headlines is typically around ``1.25``, body copy around ``1.5``, and captions somewhere in between. Because web typography has matured so much, I think that if browser defaults were first being established today, they would likely adopt these principles.\

So I feel that setting something like the following would be very much in line with the spirit of this project:

```
h1, h2, h3, h4, h5, h6 { line-height: 1.25; }

caption, figcaption, label, legend { line-height: 1.375; }

p { line-height: 1.5; }
```

**Comment by philipbordallo** [comment]
> One of my pet peeves is when developers forget to reset the line-height on headlines, and the UA default is used.

100% agree, the default of `line-height: normal` does not work well for headings.

The difficult thing about setting the `line-height` to be a different value than `normal` is that it will completely ignore the font's _em-square_ or inherit content area. Meaning there is potential for overflow or too much spacing. Vincent De Oliveira has [a good writeup about this](https://iamvdo.me/en/blog/css-font-metrics-line-height-and-vertical-align) and [here's a Codepen](https://codepen.io/philipbordallo/pen/mobJjJ) with a variety of `line-heights` and fonts that showcase what I'm talking about. 

I think @sandren's suggestion of `1.25` is a good reasonable default. But again this will always be affected by what font is used and the developer will have to change it accordingly.
